### ISSUE TITLE
MixinIssue

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArtixAllMighty/BadBone#10] opened 2022-05-22 06:26 UTC
https://bytebin.lucko.me/6zKSV4ySSg

**Comment by AbsolemJackdaw** [comment] 2022-05-22 06:33
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [amethyst_imbuement.mixins.json:MilkBucketMixin from mod amethyst_imbuement] from phase [DEFAULT] in config [amethyst_imbuement.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]

Im gonna go figure out what this amethyst thing does, because it seems to conflict with badbone which it shouldnt

**Comment by fzzyhmstrs** [comment] 2022-05-25 13:55
Your mixin overwrites the finishedUsingItem method, which prevents my mixin (or anybody else's mixin for this method) from ever applying.

This overwrite: [https://github.com/ArtixAllMighty/BadBone/blob/1.18-multi-loader/Fabric/src/main/java/subaraki/badbone/mixin/MixinMilkBucket.java](https://github.com/ArtixAllMighty/BadBone/blob/1.18-multi-loader/Fabric/src/main/java/subaraki/badbone/mixin/MixinMilkBucket.java)

prevents this redirect from ever finding the vanilla method: [https://github.com/fzzyhmstrs/ai/blob/master/src/main/java/me/fzzyhmstrs/amethyst_imbuement/mixins/MilkBucketMixin.java](https://github.com/fzzyhmstrs/ai/blob/master/src/main/java/me/fzzyhmstrs/amethyst_imbuement/mixins/MilkBucketMixin.java)

**Comment by fzzyhmstrs** [comment] 2022-05-25 13:59
This is the critical piece of the log, My mixin can't find the function that your mixin has already changed:

cannot inject into net/minecraft/class_1805::method_7861(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;)Lnet/minecraft/class_1799; **merged by subaraki.badbone.mixin.MixinMilkBucket** with priority 1000 [PREINJECT Applicator Phase

**Comment by AbsolemJackdaw** [comment] 2022-05-25 14:42
@strikerrocker i believe you wrote this piece of code for the fabric branch. Fix plis.

**Comment by strikerrocker** [comment] 2022-05-28 07:30
Fixed in latest release.

**Closed as completed by strikerrocker** 2022-05-28 07:30 UTC
Labels: bug
